//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        public int ID { get; set; }
        public int LocationID { get; set; }
        public string SeatName { get; set; }
        public Nullable<bool> IsFilled { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
